fix output breaks saving plot as png/svg #2359
menu entry appears but it gives

TypeError: $scope.outputDisplayModel.saveAsSvg is not a function
    at Object._saveAsItems.action (beakerApp.js:8170)

FIXED